import { expect, test } from '@playwright/test'

test('dashboard exposes core daily work', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: '登录' }).click()
  await expect(page.getByRole('heading', { name: '经营概览' })).toBeVisible()
  await expect(page.getByText('今日执行中心')).toBeVisible()
  await expect(page.getByText('会员结构')).toBeVisible()
  await page.getByRole('button', { name: /今日待办/ }).click()
  await expect(page.getByRole('heading', { name: '今日待办', level: 2 })).toBeVisible()
  await expect(page.getByText(/今天及逾期共 \d+ 项/)).toBeVisible()
  await page.getByRole('button', { name: '会员管理' }).click()
  await expect(page.getByRole('heading', { name: '会员管理', level: 2 })).toBeVisible()
  await expect(page.getByText('林女士')).toBeVisible()
  await page.getByRole('button', { name: '服务任务' }).click()
  await expect(page.getByRole('heading', { name: '服务任务', level: 2 })).toBeVisible()
  await expect(page.getByText('D3 回访')).toBeVisible()
  await expect(page.getByRole('button', { name: '批量处理所选' })).toBeVisible()
  await page.getByRole('checkbox', { name: '选择当前列表全部待处理任务' }).check()
  await expect(page.getByText(/已选 \d+ 项/)).toBeVisible()
})
